### ISSUE TITLE
Game crashes when entering sector

### ISSUE THREAD

**Issue by enormandeau** [sudasana/armcom#1]
I'm playing the Canadian campaign on 10th August - when I try to enter the zone pasted below, it crashes every time and this error is what appears in the log:

Traceback (most recent call last):
 File "armcom.py", line 15358, in <module>
 File "armcom.py", line 15193, in MainMenu
 File "armcom.py", line 14079, in RunCalendar
 File "armcom.py", line 14548, in InitCampaignDay
 File "armcom.py", line 14707, in DoCampaignDay
 File "armcom.py", line 12127, in MoveArea
 File "armcom.py", line 11095, in InitEncounter
 File "armcom.py", line 5934, in ActivateEnemies
 File "armcom.py", line 6170, in SpawnEnemy
 File "armcom.py", line 3383, in SetTerrain
ValueError: '' is not in list

I'm running version 1.02.

**Comment by enormandeau** [comment]
I asked the player for his savefile to find more about the setting where the bug is triggered.

**Comment by sudasana** [comment]
Has something to do with setting the terrain for an enemy infantry unit. In 1.02 I think that particular line would be:

` for value in INFANTRY_TERRAIN[table_row]:`

I suspect that the node_type of the player area wasn't set properly when the player moved into that area, since earlier the table_row variable is set thus:

```
 AREA_TYPES = ['A', 'B', 'C', 'D', 'F']
        table_row = AREA_TYPES.index(campaign.day_map.player_node.node_type)
```

I would look into the code in MoveArea, but it's odd for such a bug to appear so rarely.

**Comment by enormandeau** [comment]
Gregory, here is what the map looks like for this bug. The bug arises when the player enters the "to capture" area, which it appears is actually water with roads running through it! It looks like the map generation is probably the problem here.

![terrain_bug](https://cloud.githubusercontent.com/assets/1437223/24083006/614ebf14-0ca5-11e7-869d-692132f4fd02.png)

**Comment by sudasana** [comment]
The problem is when the capture mission is generated - it should not select an impassible map area to capture.

Here's the relevant code, seems like it has been a persistent problem:

 ```
# find quest map node
            player_y = campaign.day_map.player_node.y
            nodes = []
            for node in campaign.day_map.nodes:
                if node in campaign.day_map.blocked_nodes: continue
                # skip marshland nodes; should have been done by
                #  previous line but still seems to be getting through
                if node.node_type == 'E': continue
```

Any campaign day map node with node_type == 'E' (Marshland) should not even be connected to adjacent nodes, let alone allow the player to move into it. Not sure how this continues to occur.

**Comment by sudasana** [comment]
But yes you're right, at least part of the problem is in the campaign map generation. Those impassible marsh areas were a later addition and may not have been properly integrated.
